<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Enquiry page">
    <meta name="keywords" content="HTML5/CSS">
    <meta name="author" content="Duy Khang Nguyen">
    <title>Enquiry page</title>

    <link href="styles/style_new.css" rel="stylesheet">
    <link href="styles/footer.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
</head>

<body>
    <!--The footer section starts-->
    <footer>
        <h4 class="contact">CONTACT</h4>
        <div class="footer_content">
            <p>Address: A35 Bach Dang St, Ho Chi Minh city</p>
            <p>Phone: (+84) 38-748-2345</p>
            <p>Hours: 8:00 - 22:00, Mon - Sun</p>
        </div>
        <p class="copyright">© 2023 CHRONO</p>
    </footer>
    <!--The footer section ends-->
</body>

</html>
