<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Enquiry page">
    <meta name="keywords" content="HTML5/CSS">
    <meta name="author" content="Duy Khang Nguyen">
    <title>Enquiry page</title>

    <link href="styles/style_new.css" rel="stylesheet">
    <link href="styles/header.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
</head>

<body>
    <header>
        <a class="logo" href="#">CHRONO</a>
        <nav>
            <input id="check" type="checkbox">
            <label class="checkbtn" for="check">
                <span id="div-container">
                    <span class="menu-button"></span>
                    <span class="menu-button"></span>
                    <span class="menu-button"></span>
                </span>
            </label>

            <ul id="nav_bar">
                <li><a id="index" href="index.php">HOME</a></li>
                <li><a id="product" href="product.php">WATCHES</a></li>
                <li><a id="payment" href="payment.php">ORDER</a></li>
                <li><a id="about" href="about.php">ABOUT</a></li>
                <li><a id="enhancement" href="enhancements.php">ENHANCEMENTS</a></li>
                <li><a id="mgt" href="manager.php">MANAGER</a></li>    
            </ul>
        </nav>
    </header>
</body>

</html>